mod anchored_popup;
mod animated_image_preview;
mod app;
mod appearance;
mod audio_preview;
mod column_entry_bounds;
mod commands;
mod config;
mod file_entry_presentation;
mod file_entry_view;
mod floating_surface;
mod formatting;
mod icons;
mod input_blocking_space;
mod list_view;
mod measured_middle_ellipsized_text;
mod model;
mod network_connections;
mod network_preview_cache;
mod open_with;
mod operation_history;
mod operation_queue;
mod operation_queue_display;
mod operation_queue_view;
mod preview;
mod runtime_logging;
mod selection_marquee;
mod shortcuts;
mod sidebar;
mod sidebar_devices;
mod startup_index_tree;
mod startup_rendering;
mod startup_trace;
mod text_preview;
mod text_preview_gutter;
mod text_preview_loading;
mod text_preview_viewer;
mod three_column_view;
mod thumbnail_cache;
mod typography;
mod video_preview;
mod view;
mod virtual_range;
mod visible_entries;

fn main() -> iced::Result {
    runtime_logging::init_from_env();
    startup_trace::init_from_env();
    startup_trace::mark("main_entered");
    startup_rendering::apply_fast_startup_environment();
    app::run()
}
