[workspace]
members = [
    "crates/app-ui",
    "crates/desktop-linux",
    "crates/file-core",
    "crates/file-operation-store",
    "crates/thumbnails",
]
resolver = "2"

[workspace.package]
version = "0.0.3"
edition = "2021"
license = "GPL-3.0-or-later"
repository = ""

[workspace.dependencies]
dirs = "5.0"
iced = { version = "0.14", default-features = false, features = ["tokio", "advanced", "advanced-shaping", "svg", "image", "x11", "wayland", "fira-sans", "wgpu"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
notify = "6.1"
nucleo = "0.5.0"
tantivy = "0.26.1"
tempfile = "3.10"
thiserror = "1.0"
tokio = { version = "1.37", features = ["fs", "io-util", "macros", "process", "rt-multi-thread", "sync", "time"] }
tokio-util = "0.7"
trash = "3.3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
