version = 1
mode = "dark"

[colors]
background = "#141218"
on_background = "#e6e0e9"
surface = "#141218"
surface_dim = "#141218"
surface_bright = "#3b383e"
surface_container_lowest = "#0f0d13"
surface_container_low = "#1d1b20"
surface_container = "#211f24"
surface_container_high = "#2b292f"
surface_container_highest = "#36343a"
on_surface = "#e6e0e9"
on_surface_variant = "#cac4cf"
outline = "#948f99"
outline_variant = "#49454e"
primary = "#cfbdfe"
on_primary = "#36275d"
primary_container = "#4d3d75"
on_primary_container = "#e9ddff"
secondary = "#cbc2db"
on_secondary = "#332d41"
secondary_container = "#4a4458"
on_secondary_container = "#e8def8"
tertiary = "#efb8c8"
on_tertiary = "#4a2532"
tertiary_container = "#633b48"
on_tertiary_container = "#ffd9e3"
error = "#ffb4ab"
on_error = "#690005"
error_container = "#93000a"
on_error_container = "#ffdad6"
