[package]
name = "thumbnails"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
file-core = { path = "../file-core" }
image.workspace = true
resvg.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
