[package]
name = "app-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
dark-light = "2.0.0"
desktop-linux = { path = "../desktop-linux" }
dirs.workspace = true
file-core = { path = "../file-core" }
file-search = { path = "../file-search" }
file-operation-store = { path = "../file-operation-store" }
gif = "0.14.2"
iced.workspace = true
image.workspace = true
pulldown-cmark = "0.13.4"
regex = "1.12.3"
rodio = "0.22.2"
serde_json.workspace = true
thumbnails = { path = "../thumbnails" }
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml = "1.1.2"
tracing.workspace = true
tracing-journald.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
iced_runtime = "0.14"
tempfile.workspace = true
