[package]
name = "app-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ashpd = { version = "0.10.3", default-features = false, features = ["async-std"] }
blake3.workspace = true
chrono.workspace = true
dark-light = "2.0.0"
desktop-linux = { path = "../desktop-linux" }
dirs.workspace = true
file-core = { path = "../file-core" }
file-search = { path = "../file-search" }
file-operation-store = { path = "../file-operation-store" }
gif = "0.14.2"
iced.workspace = true
image.workspace = true
libc = "0.2"
lexopt.workspace = true
pulldown-cmark = "0.13.4"
regex = "1.12.3"
roxmltree = "0.20.0"
resvg.workspace = true
rodio = "0.22.2"
rustix.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
serde_json.workspace = true
thumbnails = { path = "../thumbnails" }
time.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml = "1.1.2"
tracing.workspace = true
url.workspace = true
tracing-journald.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
chrono-tz = "0.10.4"
iced_runtime = "0.14"
rusqlite = { version = "0.32.1", features = ["bundled"] }
