[package]
name = "file-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ignore = "0.4.25"
notify.workspace = true
nucleo.workspace = true
rusqlite = { version = "0.32.1", features = ["bundled"] }
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
trash.workspace = true

[dev-dependencies]
tempfile.workspace = true
